In [3]:
import pandas as pd
import numpy as np

co = pd.read_csv("data/Colorado River Basin Water Conflict Table.csv")

In [4]:
co.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,...,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0

In [6]:
co.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64

In [7]:
co.dtypes

Event                                             int64
Search Source                                    object
Newspaper                                        object
Article Title                                    object
Duplicate                                        object
Report Date                                      object
Report Year                                     float64
Event Date                                       object
Event Day                                       float64
Event Month                                     float64
Event Year                                      float64
Conflict Present                                 object
Crisis Present                                   object
Basin                                            object
HUC6                                             object
HUC2                                             object
Place                                            object
County                                           object
County FIPS                                     float64
State                                            object
State FIPS                                       object
Urban or Rural                                   object
Issue Type                                       object
Event Summary                                    object
Stakeholders                                     object
Intensity Value                                 float64
Comments                                         object
Related Observation Themes                       object
Article Text Search - water quality               int64
Article Text Search - invasive species            int64
Article Text Search - conservation                int64
Article Text Search - drought                     int64
Article Text Search - flood                       int64
Article Text Search - ground water depletion      int64
Article Text Search - depletion                   int64
Article Text Search - infrastructure              int64
Article Text Search - fish passage                int64
Article Text Search - instream water rights       int64
Article Text Search - water rights                int64
Article Text Search - intergovernmental           int64
Article Text Search - water transfers             int64
Article Text Search - navigation                  int64
Article Text Search - fish                        int64
Article Text Search - invasive                    int64
Article Text Search - diversion                   int64
Article Text Search - water diversion             int64
Article Text Search - instream                    int64
Article Text Search - aquatic                     int64
dtype: object

In [8]:
co.shape

(268, 48)

In [12]:
pd.set_option("display.max_columns", None)
co.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0

In [21]:
co['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

In [35]:
co['State'].str

In [38]:
co['State'].str.split(';').explode().value_counts()

State
AZ     81
CO     39
UT     29
NV     12
 UT    11
CA      8
 CA     8
 NM     7
 NV     7
 WY     7
 CO     6
 AZ     6
NM      6
OH      1
WY      1
TX      1
Name: count, dtype: int64

In [37]:
co['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

In [44]:
co['State'].notna()

0       True
1       True
2       True
3      False
4      False
       ...
263     True
264     True
265     True
266     True
267     True
Name: State, Length: 268, dtype: bool

In [63]:
states = co['State'].str.split(';').explode().str.strip().unique()
states

array(['CO', 'UT', nan, 'AZ', 'OH', 'NM', 'CA', 'NV', 'WY', 'TX'],
      dtype=object)

In [64]:
co['C']

AttributeError: 'numpy.ndarray' object has no attribute 'plot'